export const ROUTES = {
  onboarding: '/onboarding',
  login: '/login',
  signup: '/signup',
  unitSetup: '/unit/setup',
  unitSearch: '/unit/search',
  unitSelect: (unitId = ':unitId') => `/unit/select/${unitId}`,
  unitComplete: '/unit/complete',
  guide: '/guide',
  home: '/home',
  diet: '/diet',
  dietAdd: '/diet/add',
  dietSearch: '/diet/search',
  exercise: '/exercise',
  exerciseEquipment: '/exercise/add/equipment',
  exerciseDatasets: '/exercise/datasets',
  exerciseRoutineEdit: '/exercise/routine/edit',
  community: '/community',
  communityPopular: '/community/popular',
  communityUnit: '/community/unit',
  mypage: '/mypage',
  myPosts: '/mypage/posts',
  myGoal: '/mypage/goal',
  myNotifications: '/mypage/notifications',
  myData: '/mypage/data',
};
